// app/layout.tsx
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Mon portfolio de reliure",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fr">
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable} antialiased
          bg-[#d2b48c]                   /* marron clair */
          [background-image:
            radial-gradient(circle at 20% 20%,#a67c52 2px,transparent 0),
            radial-gradient(circle at 80% 80%,#a67c52 2px,transparent 0)
          ]
          [background-size:100px_100px]  /* taille du motif */
          [background-position:0_0,50px_50px]
          min-h-screen
        `}
      >
        {children}
      </body>
    </html>
  )
}
